export const testimonials = {
    "invisible_ink_pens": [
        { "name": "Asante", "text": "The invisible ink pen made writing secret messages so much fun!", "id": 1, "country": "Kenya" },
        { "name": "Kwame", "text": "Using this pen made me feel like a secret agent!", "id": 2, "country": "Ghana" },
        { "name": "Fatou", "text": "The ink dries quickly and doesn't smudge.", "id": 3, "country": "Senegal" },
        { "name": "Lamya", "text": "Great for keeping my notes private in class!", "id": 4, "country": "Morocco" },
        { "name": "Chinedu", "text": "Perfect for creating scavenger hunts for my kids.", "id": 5, "country": "Nigeria" },
        { "name": "Thandiwe", "text": "The invisible ink pen exceeded my expectations!", "id": 6, "country": "South Africa" },
        { "name": "Makda", "text": "My students were amazed by the invisible ink demonstrations.", "id": 7, "country": "Ethiopia" },
        { "name": "Nabil", "text": "I love how versatile this pen is for creative projects.", "id": 8, "country": "Algeria" },
        { "name": "Zahra", "text": "It's like magic watching the invisible ink appear!", "id": 9, "country": "Tunisia" },
        { "name": "Kofi", "text": "This pen is a game-changer for escape room enthusiasts.", "id": 10, "country": "Ghana" },
        { "name": "Sanaa", "text": "Highly recommend for anyone who loves surprises.", "id": 11, "country": "Egypt" },
        { "name": "Abdi", "text": "Great for writing love notes that only your partner can see!", "id": 12, "country": "Somalia" },
        { "name": "Aïcha", "text": "My grandkids absolutely loved the invisible ink pens!", "id": 13, "country": "Mauritania" },
        { "name": "Lwazi", "text": "Impressed by how long-lasting the ink is.", "id": 14, "country": "South Africa" },
        { "name": "Moussa", "text": "Using this pen adds an extra layer of excitement to any project.", "id": 15, "country": "Mali" },
        { "name": "Zara", "text": "The invisible ink pen is a must-have for any spy-themed party.", "id": 16, "country": "Kenya" },
        { "name": "Jabari", "text": "Easy to use and delivers consistently clear results.", "id": 17, "country": "Tanzania" },
        { "name": "Nadia", "text": "Brings out the kid in everyone!", "id": 18, "country": "Morocco" },
        { "name": "Akin", "text": "I've never seen anything like it – truly unique.", "id": 19, "country": "Nigeria" },
        { "name": "Nia", "text": "Makes studying much more enjoyable.", "id": 20, "country": "Kenya" },
        { "name": "Zainab", "text": "Perfect for keeping a secret diary.", "id": 21, "country": "Sudan" },
        { "name": "Diallo", "text": "It's like having a superpower in your pocket!", "id": 22, "country": "Guinea" },
        { "name": "Kwasi", "text": "Using this pen sparked my creativity like never before.", "id": 23, "country": "Ghana" },
        { "name": "Mirembe", "text": "Great for leaving surprise messages for friends and family.", "id": 24, "country": "Uganda" },
        { "name": "Tariq", "text": "The invisible ink pen adds an element of mystery to everyday tasks.", "id": 25, "country": "Algeria" },
        { "name": "Sekou", "text": "Ink is invisible even on different types of paper.", "id": 26, "country": "Mali" },
        { "name": "Makeda", "text": "My students' engagement skyrocketed with the use of invisible ink.", "id": 27, "country": "Ethiopia" },
        { "name": "Chukwu", "text": "This pen turned boring meetings into fun note-taking sessions.", "id": 28, "country": "Nigeria" },
        { "name": "Kadija", "text": "The ink flows smoothly and evenly.", "id": 29, "country": "Morocco" },
        { "name": "Sekai", "text": "Such a simple concept, yet so much fun!", "id": 30, "country": "Zimbabwe" },
        { "name": "Tendai", "text": "I feel like a kid again every time I use this pen.", "id": 31, "country": "Zimbabwe" },
        { "name": "Aminata", "text": "It's amazing how clear the ink becomes under UV light.", "id": 32, "country": "Senegal" },
        { "name": "Musa", "text": "The invisible ink pen made planning surprises for my spouse effortless.", "id": 33, "country": "Nigeria" },
        { "name": "Simba", "text": "I've already bought multiple pens as gifts for friends.", "id": 34, "country": "Tanzania" },
        { "name": "Nala", "text": "The invisible ink adds an element of mystery to my artwork.", "id": 35, "country": "South Africa" },
        { "name": "Sadeeq", "text": "Using this pen makes mundane tasks exciting.", "id": 36, "country": "Nigeria" },
        { "name": "Amina", "text": "It's like having a secret language with my friends.", "id": 37, "country": "Kenya" },
        { "name": "Abena", "text": "The pen is durable and long-lasting.", "id": 38, "country": "Ghana" },
        { "name": "Oumar", "text": "This pen is perfect for DIY escape room enthusiasts.", "id": 39, "country": "Senegal" },
        { "name": "Naledi", "text": "I love the reaction I get when people see my hidden messages.", "id": 40, "country": "South Africa" },
        { "name": "Yemi", "text": "The invisible ink pen adds a fun twist to traditional pen-and-paper games.", "id": 41, "country": "Nigeria" },
        { "name": "Juma", "text": "Great for labeling personal belongings discreetly.", "id": 42, "country": "Tanzania" },
        { "name": "Siyabonga", "text": "I never knew writing could be this entertaining!", "id": 43, "country": "South Africa" },
        { "name": "Esi", "text": "The invisible ink pen is a hit at parties.", "id": 44, "country": "Ghana" },
        { "name": "Kamau", "text": "Using this pen brings out my inner detective.", "id": 45, "country": "Kenya" },
        { "name": "Iman", "text": "Hands down, the coolest pen I've ever used!", "id": 46, "country": "Somalia" },
        { "name": "Thabo", "text": "My friends were blown away by the invisible ink pen.", "id": 47, "country": "South Africa" },
        { "name": "Bakari", "text": "Writing with this pen feels like a secret mission.", "id": 48, "country": "Kenya" },
        { "name": "Yara", "text": "The invisible ink pen is my new favorite writing tool!", "id": 49, "country": "Egypt" },
        { "name": "Sipho", "text": "With this pen, I can leave secret messages everywhere I go!", "id": 50, "country": "South Africa" }
    ],
    "anti_snore_devices": [
        { "name": "Fatima", "text": "The anti-snore device has transformed my sleep completely. Thank you!", "id": 1, "country": "Egypt" },
        { "name": "Kwame", "text": "I was skeptical at first, but this device is a game-changer. Highly recommend!", "id": 2, "country": "Ghana" },
        { "name": "Aisha", "text": "Finally, a peaceful night's sleep! This device is a miracle.", "id": 3, "country": "Nigeria" },
        { "name": "Hassan", "text": "My partner and I are both sleeping better thanks to this amazing device.", "id": 4, "country": "Morocco" },
        { "name": "Nomsa", "text": "I can't believe how much better I feel after using this anti-snore device.", "id": 5, "country": "South Africa" },
        { "name": "Amara", "text": "No more snoring means more restful nights. Thank you so much!", "id": 6, "country": "Kenya" },
        { "name": "Chinedu", "text": "I've tried everything, but this is the only thing that works.", "id": 7, "country": "Nigeria" },
        { "name": "Youssef", "text": "This device has improved my sleep quality immensely.", "id": 8, "country": "Tunisia" },
        { "name": "Fatoumata", "text": "Life-changing! My family is grateful for the peace and quiet.", "id": 9, "country": "Senegal" },
        { "name": "Ahmed", "text": "Finally, I can sleep through the night without waking up from snoring.", "id": 10, "country": "Sudan" },
        { "name": "Amina", "text": "I'm amazed by how effective this device is. Thank you!", "id": 11, "country": "Tanzania" },
        { "name": "Mpho", "text": "This product is worth every penny. I feel like a new person.", "id": 12, "country": "South Africa" },
        { "name": "Tariq", "text": "My wife is thrilled that my snoring is a thing of the past.", "id": 13, "country": "Egypt" },
        { "name": "Aïssatou", "text": "Thanks to this device, I'm waking up refreshed and energized.", "id": 14, "country": "Mali" },
        { "name": "Tunde", "text": "I've been using the anti-snore device for a week, and the results are incredible.", "id": 15, "country": "Nigeria" },
        { "name": "Fatima", "text": "I never thought I'd find relief from snoring until I tried this device.", "id": 16, "country": "Morocco" },
        { "name": "Mounir", "text": "My sleep has improved so much since using this anti-snore device.", "id": 17, "country": "Algeria" },
        { "name": "Chipo", "text": "No more complaints from my roommate about my snoring. Thank you!", "id": 18, "country": "Zimbabwe" },
        { "name": "Jamal", "text": "I'm finally getting the quality sleep I deserve.", "id": 19, "country": "Egypt" },
        { "name": "Ife", "text": "This device is a game-changer for anyone struggling with snoring.", "id": 20, "country": "Nigeria" },
        { "name": "Halima", "text": "I can't thank you enough for creating such an effective product.", "id": 21, "country": "Kenya" },
        { "name": "Sana", "text": "My husband's snoring used to keep me awake, but not anymore.", "id": 22, "country": "Morocco" },
        { "name": "Kwasi", "text": "After years of disrupted sleep, I'm finally getting the rest I need.", "id": 23, "country": "Ghana" },
        { "name": "Amina", "text": "This anti-snore device is a lifesaver. I feel like a new person.", "id": 24, "country": "Egypt" },
        { "name": "Zanele", "text": "I'm amazed at how quickly this device worked for me.", "id": 25, "country": "South Africa" },
        { "name": "Tariro", "text": "No more restless nights thanks to this incredible product.", "id": 26, "country": "Zimbabwe" },
        { "name": "Moussa", "text": "Finally, my partner and I can both sleep peacefully.", "id": 27, "country": "Senegal" },
        { "name": "Mariam", "text": "This device has restored harmony to my household.", "id": 28, "country": "Nigeria" },
        { "name": "Hicham", "text": "I'm sleeping better than I have in years. Thank you!", "id": 29, "country": "Morocco" },
        { "name": "Naledi", "text": "I can't believe I waited so long to try this device.", "id": 30, "country": "South Africa" },
        { "name": "Hassan", "text": "My snoring was affecting my relationship, but not anymore.", "id": 31, "country": "Egypt" },
        { "name": "Aïcha", "text": "I'm waking up feeling refreshed and rejuvenated.", "id": 32, "country": "Senegal" },
        { "name": "Ifeanyi", "text": "This device is a game-changer. I wish I had found it sooner.", "id": 33, "country": "Nigeria" },
        { "name": "Zahra", "text": "I've tried other solutions, but this is the only one that works for me.", "id": 34, "country": "Morocco" },
        { "name": "Ali", "text": "Thanks to this device, I'm finally getting the sleep I need.", "id": 35, "country": "Algeria" },
        { "name": "Fatou", "text": "My family is grateful for the peace and quiet at night.", "id": 36, "country": "Senegal" },
        { "name": "Lwazi", "text": "I'm sleeping soundly through the night for the first time in years.", "id": 37, "country": "South Africa" },
        { "name": "Mubarak", "text": "This device has made a world of difference for me.", "id": 38, "country": "Egypt" },
        { "name": "Amina", "text": "I'm no longer waking up exhausted thanks to this amazing device.", "id": 39, "country": "Nigeria" },
        { "name": "Zara", "text": "I can't thank you enough for creating such an effective solution.", "id": 40, "country": "Morocco" },
        { "name": "Hamza", "text": "Finally, I can sleep without worrying about disturbing others.", "id": 41, "country": "Algeria" },
        { "name": "Ifeoma", "text": "My partner and I are both thrilled with the results.", "id": 42, "country": "Nigeria" },
        { "name": "Youssef", "text": "This device has exceeded all my expectations.", "id": 43, "country": "Morocco" },
        { "name": "Sipho", "text": "I'm amazed by how quickly this device worked for me.", "id": 44, "country": "South Africa" },
        { "name": "Layla", "text": "Thanks to this device, I'm waking up feeling refreshed and energized.", "id": 45, "country": "Egypt" },
        { "name": "Tendai", "text": "No more snoring means no more sleepless nights.", "id": 46, "country": "Zimbabwe" },
        { "name": "Hassan", "text": "I'm grateful for the peace and quiet this device has brought to my home.", "id": 47, "country": "Kenya" },
        { "name": "Aïsha", "text": "This device has changed my life for the better.", "id": 48, "country": "Senegal" },
        { "name": "Tarik", "text": "I'm finally getting the restful sleep I've been longing for.", "id": 49, "country": "Morocco" },
        { "name": "Nana", "text": "Thanks to this device, I feel like a whole new person.", "id": 50, "country": "Ghana" }
    ],
    "glass_cleaners": [
        { "name": "Fatima", "text": "I am amazed by the results of this glass cleaner. It worked wonders on my car windows. Thank you!", "id": 1, "country": "Nigeria" },
        { "name": "Kwame", "text": "This glass cleaner is a game-changer. It left my car windows sparkling clean. Highly recommended!", "id": 2, "country": "Ghana" },
        { "name": "Aisha", "text": "I've tried many glass cleaners, but this one stands out. It removed all the dirt and grime from my car windows effortlessly.", "id": 3, "country": "Morocco" },
        { "name": "Tariq", "text": "I couldn't be happier with this glass cleaner. It made my car windows crystal clear. Thank you!", "id": 4, "country": "Egypt" },
        { "name": "Amira", "text": "This glass cleaner is simply the best. It removed all the smudges and streaks from my car windows. I'm impressed!", "id": 5, "country": "Tunisia" },
        { "name": "Femi", "text": "I love the results of this glass cleaner. It gave my car windows a streak-free shine. Highly satisfied!", "id": 6, "country": "Nigeria" },
        { "name": "Zainab", "text": "I'm a car enthusiast, and this glass cleaner exceeded my expectations. It made my car windows look brand new.", "id": 7, "country": "Kenya" },
        { "name": "Ahmed", "text": "I've tried many glass cleaners, but none compare to this one. It's effective and leaves no streaks on my car windows.", "id": 8, "country": "Egypt" },
        { "name": "Nour", "text": "This glass cleaner is a must-have for car owners. It removed all the stubborn stains from my car windows. Thank you!", "id": 9, "country": "Morocco" },
        { "name": "Malaika", "text": "I'm impressed with the quality of this glass cleaner. It made my car windows shine like never before.", "id": 10, "country": "Ghana" },
        { "name": "Jamal", "text": "This glass cleaner is a game-changer. It effortlessly removed all the dirt and grime from my car windows. Highly recommended!", "id": 11, "country": "Tanzania" },
        { "name": "Sara", "text": "I've tried numerous glass cleaners, but this one is by far the best. It left my car windows spotless and streak-free.", "id": 12, "country": "Egypt" },
        { "name": "Nadia", "text": "I'm amazed by the effectiveness of this glass cleaner. It made my car windows crystal clear with minimal effort.", "id": 13, "country": "Algeria" },
        { "name": "Youssef", "text": "This glass cleaner is a lifesaver. It removed all the dirt and grime from my car windows, leaving them sparkling clean.", "id": 14, "country": "Morocco" },
        { "name": "Amina", "text": "I'm thrilled with the results of this glass cleaner. It made my car windows shine like new. Highly recommended!", "id": 15, "country": "Tunisia" },
        { "name": "Jabari", "text": "I'm impressed with how well this glass cleaner works. It removed all the smudges and streaks from my car windows with ease.", "id": 16, "country": "Kenya" },
        { "name": "Malika", "text": "This glass cleaner is amazing. It made my car windows sparkle and shine. I couldn't be happier!", "id": 17, "country": "Algeria" },
        { "name": "Hassan", "text": "I've tried many glass cleaners, but this one is my favorite. It left my car windows streak-free and crystal clear.", "id": 18, "country": "Morocco" },
        { "name": "Nadia", "text": "This glass cleaner exceeded my expectations. It made my car windows shine like never before. Highly satisfied!", "id": 19, "country": "Egypt" },
        { "name": "Zara", "text": "I'm amazed by how well this glass cleaner works. It removed all the dirt and grime from my car windows, leaving them sparkling clean.", "id": 20, "country": "Kenya" }
    ]
}
